# Generated by Django 5.0.6 on 2024-07-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
