# Generated by Django 5.0.6 on 2024-07-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_remove_doctor_available_time_doctor_available_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctor'},
        ),
    ]
