# Generated by Django 5.0.6 on 2024-07-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0008_alter_doctor_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
