# Generated by Django 5.0.6 on 2024-07-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
