# Generated by Django 5.0.6 on 2024-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_remove_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointent_types',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=10),
        ),
    ]
